config/routes.rb
Rails.application.routes.draw do
  # get 'restaurants/index'
  # get 'restaurants/show'
  root to: 'restaurants#new'
  resources :restaurants do
    resources :menus
  end

  resources :menus do
    resources :items
    resources :orders
  end
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :menu
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :items
  has_many :orders

  has_many :order_items, through: :orders, source: :items

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :menu

  has_and_belongs_to_many :items

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :menus

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def create
        @menu = Menu.find(params[:menu_id])
        @item = @menu.items.create(item_params)
        redirect_to menu_path(@menu)
      end
      
      private
      def item_params
        params.require(:item).permit(:name, :description, :price)
      end
      
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    def create
        @restaurant = Restaurant.find(params[:restaurant_id])
        @menu = @restaurant.menus.create(menu_params)
        redirect_to restaurant_path(@restaurant)
      end
      
      private
      def menu_params
        params.require(:menu).permit(:name)
      end
      
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def create
        @menu = Menu.find(params[:menu_id])
        @order = @menu.orders.create(order_params)
        redirect_to menu_path(@menu)
      end
      
      def update
        @menu = Menu.find(params[:menu_id])
        @order = @menu.orders.find(params[:id])
        if @order.update(order_params)
        redirect_to menu_order_path(@menu, @order)
        else
        render 'edit'
        end
        end
        
        private
        def order_params
        params.require(:order).permit(:name, :address, :phone, item_ids: [])
        end

     
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end
  
  private
  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/items/_form.html.erb
<%= form_for [@menu, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<p><%= @item.description %></p>

<p><strong>Price:</strong> $<%= @item.price %></p>

<%= link_to 'Edit Item', edit_menu_item_path(@menu, @item) %>
<%= link_to 'Delete Item', [@menu, @item], method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDeliveryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_for [@restaurant, @menu] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/menus/show.html.erb
<h1><%= @menu.name %></h1>

<%= link_to 'Edit Menu', edit_restaurant_menu_path(@restaurant, @menu) %>
<%= link_to 'Delete Menu', [@restaurant, @menu], method: :delete, data: { confirm: 'Are you sure?' } %>

<h2>Items</h2>

<ul>
  <% @menu.items.each do |item| %>
    <li><%= link_to item.name, menu_item_path(@menu, item) %></li>
  <% end %>
</ul>

<%= link_to 'Add New Item', new_menu_item_path(@menu) %>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>
<%= form_with(model: [@menu, @order], local: true) do |form| %>
<%= form.label :name %>
<%= form.text_field :name %>

<%= form.label :address %>
<%= form.text_area :address %>

<%= form.label :phone %>
<%= form.text_field :phone %>

  <h2>Order Items</h2>
  <ul>
    <% @menu.items.each do |item| %>
      <li>
        <%= check_box_tag "order[item_ids][]", item.id, @order.items.include?(item) %>
        <%= item.name %> ($<%= item.price %>)
      </li>
    <% end %>
  </ul>
<%= form.submit %>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_with(model: [@menu, @order], local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :address %>
  <%= form.text_area :address %>

  <%= form.label :phone %>
  <%= form.text_field :phone %>

  <%= form.submit %>
<% end %>

app/views/orders/show.html.erb
<h1>Order Details</h1>

<p><strong>Name:</strong> <%= @order.name %></p>

<p><strong>Address:</strong> <%= @order.address %></p>

<p><strong>Phone:</strong> <%= @order.phone %></p>

<p><strong>Total:</strong> $<%= @order.total %></p>

<p><strong>Status:</strong> <%= @order.status %></p>

<%= link_to 'Edit Order', edit_menu_order_path(@menu, @order) %>
<%= link_to 'Delete Order', [@menu, @order], method: :delete, data: { confirm: 'Are you sure?' } %>

<h2>Order Items</h2>
<ul>
  <% @order.items.each do |item| %>
    <li>
      <%= item.name %> ($<%= item.price %>)
    </li>
  <% end %>
</ul>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>


  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant %></li>
  <% end %>
</ul>

<%= link_to 'Add New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.description %></p>

<%= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete Restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>

<h2>Menus</h2>

<ul>
  <% @restaurant.menus.each do |menu| %>
    <li><%= link_to menu.name, restaurant_menu_path(@restaurant, menu) %></li>
  <% end %>
</ul>

<%= link_to 'Add New Menu', new_restaurant_menu_path(@restaurant) %>